# Generated by Django 5.2.5 on 2025-09-16 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_discipline_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_site.discipline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_site.student')),
            ],
        ),
    ]
