# Generated by Django 5.2.5 on 2025-09-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_studentdiscipline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDiscipline',
            new_name='StudentDisciplineMark',
        ),
    ]
