# Generated by Django 5.2.5 on 2025-09-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0005_rename_studentdiscipline_studentdisciplinemark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentDisciplineMark',
        ),
    ]
