# Generated by Django 5.2.5 on 2025-09-16 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0006_delete_studentdisciplinemark'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDisciplineMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_site.discipline')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_site.mark')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_site.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'discipline'), name='unique_student_discipline')],
            },
        ),
    ]
