# Generated by Django 5.2.5 on 2025-10-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0007_studentdisciplinemark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='name',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('зачет', 'Зачет'), ('незачет', 'Незачет')], max_length=50, unique=True),
        ),
    ]
